{% set name = "hijri-converter" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hijri-converter-{{ version }}.tar.gz
  sha256: 069b6789291e0830f4860a79dcd34fb3ceea3b95516ed4010202b9656ba1ab61

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - hijri_converter
    - hijri_converter.locales
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mhalshehri/hijri-converter
  summary: Accurate Hijri-Gregorian dates converter based on the Umm al-Qura calendar
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mhalshehri
    - synapticarbors
