{% set name = "hijri-converter" %}
{% set version = "2.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8fe17b624532665c1a4ddbe438047076ad6c8f03dbc27ac6d06f7a7a13f10956

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - hijri_converter
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/dralshehri/hijri-converter
  summary: Accurate Hijri-Gregorian dates converter based on the Umm al-Qura calendar
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dralshehri
    - synapticarbors
