{% set name = "hijri-converter" %}
{% set version = "2.3.2.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 986657ccd83a5beaf233ce5a219645747e885c45d4833bd2a8fa1b927fa39570

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - hijri_converter
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/dralshehri/hijri-converter
  summary: Accurate Hijri-Gregorian dates converter based on the Umm al-Qura calendar
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dralshehri
    - synapticarbors
